# Generated by Django 6.0.3 on 2026-04-30 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('mesures_par_defaut', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Couturier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_atelier', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='couturiers/')),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('delai_moyen_livraison', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='couturier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Couturier',
                'verbose_name_plural': 'Couturiers',
            },
        ),
    ]
