# Generated by Django 6.0.3 on 2026-04-30 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('qualite_travail', models.IntegerField(default=0)),
                ('respect_delais', models.IntegerField(default=0)),
                ('communication', models.IntegerField(default=0)),
                ('rapport_qualite_prix', models.IntegerField(default=0)),
                ('photos', models.JSONField(blank=True, default=list, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to='users.client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='orders.commande')),
                ('couturier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='users.couturier')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_creation'],
                'unique_together': {('couturier', 'client', 'commande')},
            },
        ),
    ]
