# Generated by Django 6.0.3 on 2026-04-30 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type_modele', models.CharField(choices=[('robe', 'Robe'), ('chemise', 'Chemise'), ('pantalon', 'Pantalon'), ('costume', 'Costume'), ('jupe', 'Jupe'), ('veste', 'Veste'), ('blouse', 'Blouse'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('niveau_difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Format accepté: JPG, PNG, GIF. Taille max: 5MB', null=True, upload_to='modeles/')),
                ('visible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
                ('temps_realisation', models.IntegerField(default=7)),
                ('materiau_recommandé', models.CharField(blank=True, max_length=100, null=True)),
                ('couleurs_disponibles', models.JSONField(blank=True, default=list, null=True)),
                ('vues', models.IntegerField(default=0)),
                ('commandes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couturier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='users.couturier')),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'ordering': ['-created_at'],
            },
        ),
    ]
