# Generated by Django 6.0.3 on 2026-04-30 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mesures_client', models.JSONField(blank=True, default=dict, null=True)),
                ('taille', models.CharField(blank=True, max_length=20, null=True)),
                ('couleurs', models.CharField(blank=True, max_length=200, null=True)),
                ('preferences', models.TextField(blank=True, null=True)),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acompte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], max_length=50, null=True)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('priorite', models.IntegerField(default=1)),
                ('notes_internes', models.TextField(blank=True, null=True)),
                ('raison_annulation', models.TextField(blank=True, null=True)),
                ('photos_client', models.JSONField(blank=True, default=list, null=True)),
                ('photos_couturier', models.JSONField(blank=True, default=list, null=True)),
                ('satisfait_client', models.BooleanField(blank=True, null=True)),
                ('commentaire_final', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='users.client')),
                ('couturier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_recues', to='users.couturier')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='catalog.modele')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
    ]
